services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/ev_charging?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - JWT_SECRET=your-super-secret-jwt-key
      - PORT=8080
    depends_on:
      - postgres
      - redis
    networks:
      - ev-charging-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ev_charging
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ev-charging-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ev-charging-network

volumes:
  postgres_data:
  redis_data:

networks:
  ev-charging-network:
    driver: bridge
